apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: happyimage
  type: NodePort
  ports:
    - protocol: TCP
      port: 30008      # The port you want to expose on the service
      targetPort: 80
